import pandas as pd
a=input()
df=pd.read_csv(a)
vel=df['Velocidade do Vento {m/s}'].mean()
den=df['Densidade do ar {kg/m3}'].max()
ent=df['Entalpia {BTU/LB}'].min()
dir=df.query("Dia == 5 and Mes == 1")['Direcao do Vento {graus}'].mean()
qua=len(df.query("17<=`T. Pto Orvalho {C}`<=18"))
mes=df.groupby("Mes")["Velocidade do Vento {m/s}"].median().astype('int64')
rad=len(df.query("200<=`Rad Direta Normal {Wh/m2}` and 0<=`Rad Difusa Horizontal {Wh/m2}`<=100"))
x=df.query("200<=`Rad Direta Normal {Wh/m2}` and 0<=`Rad Difusa Horizontal {Wh/m2}`<=100")
print(f"Media da velocidade do vento: {vel:.2f} m/s")
print(f"Maxima densidade do ar: {den:.2f} kg/m3")
print(f"Entalpia minima: {ent:.2f} btu/lb")
print(f"Media da direcao do vento no dia 5 do mes 1: {dir:.2f} graus")
print("Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:", qua)
print(mes)
print("Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero")
print("Quantidade:", rad)
print("10 primeiros:")
print(x[["Mes", "Dia", "Hora", "Rad Direta {Wh/m2}"]].head(10))